packages:
  - apps/*
  - docs
  - packages/*

catalog:
  "@callstack/react-theme-provider": ^3.0.9
  "@eslint/js": ^10.0.1
  "@jest/globals": ^30.2.0
  "@particle/dbus-next": ^0.11.4
  "@reduxjs/toolkit": ^2.11.2
  "@types/node": ^25.3.5
  "@types/react": ^19.2.14
  "@types/react-dom": ^19.2.3
  "@types/yargs": ^17.0.35
  "@typescript-eslint/eslint-plugin": ^8.56.1
  "@typescript-eslint/parser": ^8.56.1
  "@vitejs/plugin-react": ^5.1.4
  "@wnayes/electron-redux": 2.0.0-alpha.11
  electron: ^40.8.0
  esbuild: ^0.27.3
  eslint: ^10.0.3
  eslint-plugin-prettier: ^5.5.5
  eslint-plugin-react-hooks: ^7.0.1
  freedesktop-desktop-entry: ^1.0.0
  freedesktop-icons: ^1.0.0
  globals: ^17.4.0
  jest: ^30.2.0
  prettier: 3.8.1
  react: ^19.2.4
  react-dom: ^19.2.4
  react-error-boundary: ^6.1.1
  react-redux: ^9.2.0
  redux: ^5.0.1
  rfc4648: ^1.5.4
  ts-jest: ^29.4.6
  tslib: ^2.8.1
  turbo: ^2.8.14
  type-fest: ^5.4.4
  typescript: ~5.9.3
  typescript-eslint: ^8.56.1
  vite: ^7.3.1
  vite-node: ^5.3.0
  x11: ^2.3.0
  xdg-user-dir: ^0.0.1
  yargs: ^18.0.0

onlyBuiltDependencies:
  - core-js
  - core-js-pure
  - electron
  - esbuild
