export const defaultCategories: Record<string, string> = {
    "AudioVideo": "Audio / Video",
    "Audio": "Audio",
    "Video": "Video",
    "Development": "Development",
    "Education": "Education",
    "Game": "Game",
    "Graphics": "Graphics",
    "Network": "Network",
    "Office": "Office",
    "Science": "Science",
    "Settings": "Settings",
    "System": "System",
    "Utility": "Utility",
    "Building": "Building",
    "Debugger": "Debugger",
    "IDE": "IDE",
    "GUIDesigner": "GUI Designer",
    "Profiling": "Profiling",
    "RevisionControl": "Revision Control",
    "Translation": "Translation",
    "Calendar": "Calendar",
    "ContactManagement": "Contact Management",
    "Database": "Database",
    "Dictionary": "Dictionary",
    "Chart": "Chart",
    "Email": "Email",
    "Finance": "Finance",
    "FlowChart": "Flow Chart",
    "PDA": "PDA",
    "ProjectManagement": "Project Management",
    "Presentation": "Presentation",
    "Spreadsheet": "Spreadsheet",
    "WordProcessor": "Word Processor",
    "2DGraphics": "2D Graphics",
    "VectorGraphics": "Vector Graphics",
    "RasterGraphics": "Raster Graphics",
    "3DGraphics": "3D Graphics",
    "Scanning": "Scanning",
    "OCR": "Optical Character Recognition (OCR)",
    "Photography": "Photography",
    "Publishing": "Publishing",
    "Viewer": "Viewer",
    "TextTools": "Text Tools",
    "DesktopSettings": "Desktop Settings",
    "HardwareSettings": "Hardware Settings",
    "Printing": "Printing",
    "PackageManager": "Package Manager",
    "Dialup": "Dial-up",
    "InstantMessaging": "Instant Messaging",
    "Chat": "Chat",
    "IRCClient": "IRC Client",
    "Feed": "Feed",
    "FileTransfer": "File Transfer",
    "HamRadio": "HAM Radio",
    "News": "News",
    "P2P": "Peer-to-Peer (P2P)",
    "RemoteAccess": "Remote Access",
    "Telephony": "Telephony",
    "TelephonyTools": "Telephony Tools",
    "VideoConference": "Video Conference",
    "WebBrowser": "Web Browser",
    "WebDevelopment": "Web Development",
    "Midi": "MIDI",
    "Mixer": "Mixer",
    "Sequencer": "Sequencer",
    "Tuner": "Tuner",
    "TV": "TV",
    "AudioVideoEditing": "Audio / Video Editing",
    "Player": "Player",
    "Recorder": "Recorder",
    "DiscBurning": "Disc Burning",
    "ActionGame": "Action Game",
    "AdventureGame": "Adventure Game",
    "ArcadeGame": "Arcade Game",
    "BoardGame": "Board Game",
    "BlocksGame": "Blocks Game",
    "CardGame": "Card Game",
    "KidsGame": "Kids Game",
    "LogicGame": "Logic Game",
    "RolePlaying": "Role-Playing Game",
    "Shooter": "Shooter Game",
    "Simulation": "Simulation Game",
    "SportsGame": "Sports Game",
    "StrategyGame": "Strategy Game",
    "Art": "Art",
    "Construction": "Construction",
    "Music": "Music",
    "Languages": "Languages",
    "ArtificialIntelligence": "Artificial Intelligence",
    "Astronomy": "Astronomy",
    "Biology": "Biology",
    "Chemistry": "Chemistry",
    "ComputerScience": "Computer Science",
    "DataVisualization": "Data Visualization",
    "Economy": "Economy",
    "Electricity": "Electricity",
    "Geography": "Geography",
    "Geology": "Geology",
    "Geoscience": "Geoscience",
    "History": "History",
    "Humanities": "Humanities",
    "ImageProcessing": "Image Processing",
    "Literature": "Literature",
    "Maps": "Maps",
    "Math": "Math",
    "NumericalAnalysis": "Numerical Analysis",
    "MedicalSoftware": "Medical Software",
    "Physics": "Physics",
    "Robotics": "Robotics",
    "Spirituality": "Spirituality",
    "Sports": "Sports",
    "ParallelComputing": "Parallel Computing",
    "Amusement": "Amusement",
    "Archiving": "Archiving",
    "Compression": "Compression",
    "Electronics": "Electronics",
    "Emulator": "Emulator",
    "Engineering": "Engineering",
    "FileTools": "File Tools",
    "FileManager": "File Manager",
    "TerminalEmulator": "Terminal Emulator",
    "Filesystem": "File System",
    "Monitor": "Monitor",
    "Security": "Security",
    "Accessibility": "Accessibility",
    "Calculator": "Calculator",
    "Clock": "Clock",
    "TextEditor": "Text Editor",
    "Documentation": "Documentation",
    "Adult": "Adult",
    "Core": "Core",
    "KDE": "KDE",
    "COSMIC": "COSMIC",
    "GNOME": "GNOME",
    "XFCE": "XFCE",
    "DDE": "DDE",
    "GTK": "GTK",
    "Qt": "Qt",
    "Motif": "Motif",
    "Java": "Java",
    "ConsoleOnly": "Console Only"
};
